### ISSUE TITLE
jsonnet_mapper attribute in config doesn't add the `base64://` prefix

### ISSUE THREAD

**Issue by shipperizer** [canonical/kratos-operator#331]
### Bug Description

when setting the jsonnet_mapper config attribute in `kratos-external-idp-configurator` the final kratos config gets damaged

the `base64://` prefix is missing from the k8s configmap 

### To Reproduce

```
juju  deploy kratos --channel=latest/edge
juju deploy kratos-external-idp-configurator generic-oidc --channel=latest/edge
juju config generic-oidc jsonnet_mapper="$(cat hydra.jsonnet)"
juju integrate kratos generic-oidc
```

### Environment

```
juju show-unit kratos/0


  - relation-id: 23
    endpoint: kratos-external-idp
    related-endpoint: kratos-external-idp
    application-data:
      providers: '[{"client_id": "**************************", "provider":
        "generic", "secret_backend": "relation", "scope": "openid profile email offline_access",
        "jsonnet_mapper": "local claims = std.extVar(''claims'');\n\n{\n  identity:
        {\n    traits: {\n      [if ''email'' in claims then ''email'' else null]:
        claims.email,\n      [if ''name'' in claims then ''name'' else null]: claims.name,\n      [if
        ''given_name'' in claims then ''given_name'' else null]: claims.given_name,\n      [if
        ''family_name'' in claims then ''family_name'' else null]: claims.family_name,\n      [if
        ''last_name'' in claims then ''last_name'' else null]: claims.last_name,\n      [if
        ''middle_name'' in claims then ''middle_name'' else null]: claims.middle_name,\n      [if
        ''nickname'' in claims then ''nickname'' else null]: claims.nickname,\n      [if
        ''preferred_username'' in claims then ''preferred_username'' else null]: claims.preferred_username,\n      [if
        ''profile'' in claims then ''profile'' else null]: claims.profile,\n      [if
        ''picture'' in claims then ''picture'' else null]: claims.picture,\n      [if
        ''website'' in claims then ''website'' else null]: claims.website,\n      [if
        ''gender'' in claims then ''gender'' else null]: claims.gender,\n      [if
        ''birthdate'' in claims then ''birthdate'' else null]: claims.birthdate,\n      [if
        ''zoneinfo'' in claims then ''zoneinfo'' else null]: claims.zoneinfo,\n      [if
        ''phone_number'' in claims && claims.phone_number_verified then ''phone_number''
        else null]: claims.phone_number,\n      [if ''locale'' in claims then ''locale''
        else null]: claims.locale,\n      [if ''team'' in claims then ''team'' else
        null]: claims.team,\n    },\n  },\n}", "client_secret": "***********************",
        "issuer_url": "***********************"}]'
    related-units:
      canonical-oidc/0:
        in-scope: true
        data:
          egress-subnets: 10.200.96.31/32
```

```
kubectl describe cm kratos-config

            enabled: True
        oidc:
            config:
                providers:
                    
                    - id: google_canonical
                      client_id: **************************
                      provider: google
                      label: google
                      client_secret: **************************
                      scope: ['profile', 'email', 'address', 'phone']
                      
                      mapper_url: "base64://bG9jYWwgY2xhaW1zID0gewogIGVtYWlsX3ZlcmlmaWVkOiBmYWxzZSwKfSArIHN0ZC5leHRWYXIoJ2NsYWltcycpOwoKewogIGlkZW50aXR5OiB7CiAgICB0cmFpdHM6IHsKICAgICAgW2lmICdlbWFpbCcgaW4gY2xhaW1zICYmIGNsYWltcy5lbWFpbF92ZXJpZmllZCB0aGVuICdlbWFpbCcgZWxzZSBudWxsXTogY2xhaW1zLmVtYWlsLAogICAgICBbaWYgJ25hbWUnIGluIGNsYWltcyB0aGVuICduYW1lJyBlbHNlIG51bGxdOiBjbGFpbXMubmFtZSwKICAgICAgW2lmICdnaXZlbl9uYW1lJyBpbiBjbGFpbXMgdGhlbiAnZ2l2ZW5fbmFtZScgZWxzZSBudWxsXTogY2xhaW1zLmdpdmVuX25hbWUsCiAgICAgIFtpZiAnZmFtaWx5X25hbWUnIGluIGNsYWltcyB0aGVuICdmYW1pbHlfbmFtZScgZWxzZSBudWxsXTogY2xhaW1zLmZhbWlseV9uYW1lLAogICAgICBbaWYgJ2xhc3RfbmFtZScgaW4gY2xhaW1zIHRoZW4gJ2xhc3RfbmFtZScgZWxzZSBudWxsXTogY2xhaW1zLmxhc3RfbmFtZSwKICAgICAgW2lmICdtaWRkbGVfbmFtZScgaW4gY2xhaW1zIHRoZW4gJ21pZGRsZV9uYW1lJyBlbHNlIG51bGxdOiBjbGFpbXMubWlkZGxlX25hbWUsCiAgICAgIFtpZiAnbmlja25hbWUnIGluIGNsYWltcyB0aGVuICduaWNrbmFtZScgZWxzZSBudWxsXTogY2xhaW1zLm5pY2tuYW1lLAogICAgICBbaWYgJ3ByZWZlcnJlZF91c2VybmFtZScgaW4gY2xhaW1zIHRoZW4gJ3ByZWZlcnJlZF91c2VybmFtZScgZWxzZSBudWxsXTogY2xhaW1zLnByZWZlcnJlZF91c2VybmFtZSwKICAgICAgW2lmICdwcm9maWxlJyBpbiBjbGFpbXMgdGhlbiAncHJvZmlsZScgZWxzZSBudWxsXTogY2xhaW1zLnByb2ZpbGUsCiAgICAgIFtpZiAncGljdHVyZScgaW4gY2xhaW1zIHRoZW4gJ3BpY3R1cmUnIGVsc2UgbnVsbF06IGNsYWltcy5waWN0dXJlLAogICAgICBbaWYgJ3dlYnNpdGUnIGluIGNsYWltcyB0aGVuICd3ZWJzaXRlJyBlbHNlIG51bGxdOiBjbGFpbXMud2Vic2l0ZSwKICAgICAgW2lmICdnZW5kZXInIGluIGNsYWltcyB0aGVuICdnZW5kZXInIGVsc2UgbnVsbF06IGNsYWltcy5nZW5kZXIsCiAgICAgIFtpZiAnYmlydGhkYXRlJyBpbiBjbGFpbXMgdGhlbiAnYmlydGhkYXRlJyBlbHNlIG51bGxdOiBjbGFpbXMuYmlydGhkYXRlLAogICAgICBbaWYgJ3pvbmVpbmZvJyBpbiBjbGFpbXMgdGhlbiAnem9uZWluZm8nIGVsc2UgbnVsbF06IGNsYWltcy56b25laW5mbywKICAgICAgW2lmICdwaG9uZV9udW1iZXInIGluIGNsYWltcyAmJiBjbGFpbXMucGhvbmVfbnVtYmVyX3ZlcmlmaWVkIHRoZW4gJ3Bob25lX251bWJlcicgZWxzZSBudWxsXTogY2xhaW1zLnBob25lX251bWJlciwKICAgICAgW2lmICdsb2NhbGUnIGluIGNsYWltcyB0aGVuICdsb2NhbGUnIGVsc2UgbnVsbF06IGNsYWltcy5sb2NhbGUsCiAgICAgIFtpZiAndGVhbScgaW4gY2xhaW1zIHRoZW4gJ3RlYW0nIGVsc2UgbnVsbF06IGNsYWltcy50ZWFtLAogICAgfSwKICB9LAp9Cg=="
                    
                    - id: generic_0ff3e05c8b1a28550a058de94a52637821c45d11
                      client_id: **************************
                      provider: generic
                      label: generic
                      client_secret: **************************
                      issuer_url: **************************
                      scope: ['openid', 'profile', 'email', 'offline_access']
                      mapper_url: bG9jYWwgY2xhaW1zID0gc3RkLmV4dFZhcignY2xhaW1zJyk7Cgp7CiAgaWRlbnRpdHk6IHsKICAgIHRyYWl0czogewogICAgICBbaWYgJ2VtYWlsJyBpbiBjbGFpbXMgdGhlbiAnZW1haWwnIGVsc2UgbnVsbF06IGNsYWltcy5lbWFpbCwKICAgICAgW2lmICduYW1lJyBpbiBjbGFpbXMgdGhlbiAnbmFtZScgZWxzZSBudWxsXTogY2xhaW1zLm5hbWUsCiAgICAgIFtpZiAnZ2l2ZW5fbmFtZScgaW4gY2xhaW1zIHRoZW4gJ2dpdmVuX25hbWUnIGVsc2UgbnVsbF06IGNsYWltcy5naXZlbl9uYW1lLAogICAgICBbaWYgJ2ZhbWlseV9uYW1lJyBpbiBjbGFpbXMgdGhlbiAnZmFtaWx5X25hbWUnIGVsc2UgbnVsbF06IGNsYWltcy5mYW1pbHlfbmFtZSwKICAgICAgW2lmICdsYXN0X25hbWUnIGluIGNsYWltcyB0aGVuICdsYXN0X25hbWUnIGVsc2UgbnVsbF06IGNsYWltcy5sYXN0X25hbWUsCiAgICAgIFtpZiAnbWlkZGxlX25hbWUnIGluIGNsYWltcyB0aGVuICdtaWRkbGVfbmFtZScgZWxzZSBudWxsXTogY2xhaW1zLm1pZGRsZV9uYW1lLAogICAgICBbaWYgJ25pY2tuYW1lJyBpbiBjbGFpbXMgdGhlbiAnbmlja25hbWUnIGVsc2UgbnVsbF06IGNsYWltcy5uaWNrbmFtZSwKICAgICAgW2lmICdwcmVmZXJyZWRfdXNlcm5hbWUnIGluIGNsYWltcyB0aGVuICdwcmVmZXJyZWRfdXNlcm5hbWUnIGVsc2UgbnVsbF06IGNsYWltcy5wcmVmZXJyZWRfdXNlcm5hbWUsCiAgICAgIFtpZiAncHJvZmlsZScgaW4gY2xhaW1zIHRoZW4gJ3Byb2ZpbGUnIGVsc2UgbnVsbF06IGNsYWltcy5wcm9maWxlLAogICAgICBbaWYgJ3BpY3R1cmUnIGluIGNsYWltcyB0aGVuICdwaWN0dXJlJyBlbHNlIG51bGxdOiBjbGFpbXMucGljdHVyZSwKICAgICAgW2lmICd3ZWJzaXRlJyBpbiBjbGFpbXMgdGhlbiAnd2Vic2l0ZScgZWxzZSBudWxsXTogY2xhaW1zLndlYnNpdGUsCiAgICAgIFtpZiAnZ2VuZGVyJyBpbiBjbGFpbXMgdGhlbiAnZ2VuZGVyJyBlbHNlIG51bGxdOiBjbGFpbXMuZ2VuZGVyLAogICAgICBbaWYgJ2JpcnRoZGF0ZScgaW4gY2xhaW1zIHRoZW4gJ2JpcnRoZGF0ZScgZWxzZSBudWxsXTogY2xhaW1zLmJpcnRoZGF0ZSwKICAgICAgW2lmICd6b25laW5mbycgaW4gY2xhaW1zIHRoZW4gJ3pvbmVpbmZvJyBlbHNlIG51bGxdOiBjbGFpbXMuem9uZWluZm8sCiAgICAgIFtpZiAncGhvbmVfbnVtYmVyJyBpbiBjbGFpbXMgJiYgY2xhaW1zLnBob25lX251bWJlcl92ZXJpZmllZCB0aGVuICdwaG9uZV9udW1iZXInIGVsc2UgbnVsbF06IGNsYWltcy5waG9uZV9udW1iZXIsCiAgICAgIFtpZiAnbG9jYWxlJyBpbiBjbGFpbXMgdGhlbiAnbG9jYWxlJyBlbHNlIG51bGxdOiBjbGFpbXMubG9jYWxlLAogICAgICBbaWYgJ3RlYW0nIGluIGNsYWltcyB0aGVuICd0ZWFtJyBlbHNlIG51bGxdOiBjbGFpbXMudGVhbSwKICAgIH0sCiAgfSwKfQ==
                      
            enabled: True

```

### Relevant log output

```shell
---
```
